[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.3",
    "pycoingecko>=3.2.0",
    "requests>=2.32.5",
    "tessa>=0.9.0",
    "yfinance>=0.2.66",
]
